**1- Determine the types of the below-given variables:**

- Age
- Salary
- Income
- Customer type
- Stock price

- Age -> Continous Ratio Variable
- Salary -> Continous Ratio Variable
- Income -> Continous Ratio Variable
- Customer Type -> Categorical Nominal Variable
- Stock Price -> Continous Ratio Variable

**2- Using the movie data, we have studied in this lesson. Complete the following tasks:**

- Select a variable from the movie dataset and discuss the variable type of this variable
- Categorize a variable of your choice and assign a name to it
- Count the number of rows for each category

In [2]:
import pandas as pd
import numpy as np
movie = pd.read_csv("https://bootrain-lms-assets.s3.eu-central-1.amazonaws.com/bootrain-lms-static/datasets/movie.csv")

In [3]:
display(movie)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [4]:
display(movie.budget.dropna())

0       237000000.0
1       300000000.0
2       245000000.0
3       250000000.0
5       263700000.0
           ...
5035         7000.0
5036         3250.0
5037         9000.0
5040         1400.0
5042         1100.0
Name: budget, Length: 4551, dtype: float64

"budget" is a numerical value, that can have infinite float values. So we can take this variable as a "Continous Variable" becuase it have infinite value and when we want to compare these values we can ratio these variables. So we can say this type of value are a "Ratio Variables".

In [5]:
def make_smth(budget):
    if budget > 50000000:
        return "Huge budget"
    elif (budget <= 50000000) and (budget>15000000):
        return "Normal budget"
    elif (budget > 0 ) and (budget<=15000000): 
            return "Tiny budget"
    else:
        return "Unknown"
        
movie["budget_group"] = movie["budget"].apply(make_smth)

print(movie["budget_group"].value_counts())

Tiny budget      2032
Normal budget    1574
Huge budget       945
Unknown           492
Name: budget_group, dtype: int64

In [6]:
movie.nunique()

color                           2
director_name                2398
num_critic_for_reviews        528
duration                      191
director_facebook_likes       435
actor_3_facebook_likes        906
actor_2_name                 3032
actor_1_facebook_likes        878
gross                        4035
genres                        914
actor_1_name                 2097
movie_title                  4917
num_voted_users              4826
cast_total_facebook_likes    3978
actor_3_name                 3521
facenumber_in_poster           19
plot_keywords                4760
movie_imdb_link              4919
num_user_for_reviews          954
language                       47
country                        65
content_rating                 18
budget                        439
title_year                     91
actor_2_facebook_likes        917
imdb_score                     78
aspect_ratio                   22
movie_facebook_likes          876
budget_group                    4
dtype: int64

This is a list of unique variables in each columns

**3- Is it possible to convert categorical variable into numerical one? If so, how can you make that?**

In [7]:
def make_numeric(language):
    if language == "English":
        return 1
    else:
        return 0

movie["Is this movies English?"] = movie["language"].apply(make_numeric)

display(movie["Is this movies English?"])

0       1
1       1
2       1
3       1
4       0
       ..
5038    1
5039    1
5040    1
5041    1
5042    1
Name: Is this movies English?, Length: 5043, dtype: int64

I created a numeric value is change by categorical variable.

**4- While continuous data is generally preferred over discrete data, please indicate circumstances where discrete is the preferred data type although continuous data is available for the same characteristic.**

If we talk about certain values or some math operations' results like sum(),count() and we want to take these values at certain time, gap and category. We are using discrete data.

**5- While continuous data is measured and attribute data is counted, there is sometimes confusion if some specific dataset should be considered continuous or attribute. Provide some examples of confusing datasets and your inference.**

We can only count a attribute data. In this example, we can count how much movie in color or not:

In [8]:
movie.color.value_counts()

Color               4815
 Black and White     209
Name: color, dtype: int64

In order to this example we can measure how much budget spend in a movie. It has infinite bounds and value. Of course we can use count on budget but When we use count, continous data turns a categorical data.